version: '3'
services:
  app:
    build: .
    container_name: app-container
    ports:
      - "8080:5000"
    environment:
      - REDIS_NAME=redis
    depends_on:
      - redis
  redis:
    image: redis
