version: '2'
services:
  app:
    build: .
    environment:
      - REDIS_URL=redis://redis_db:6379
    ports:
      - "5000:5000"
    volumes:
          - .:/code

    depends_on:
      - redis_db
  redis:
    image: redis

